import { useState, useEffect } from 'react';
import { LengthVariations, getLengthVariations, LengthVariation } from '@/services/aiService';
import { Copy, CheckCircle2, ArrowRight, RefreshCw, FileText, AlignLeft, BookOpen, Download, ChevronDown } from 'lucide-react';
import { toast } from 'sonner';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { cn } from '@/lib/utils';

interface LengthVariationsDropdownProps {
  text: string;
  onApplyToWorkspace: (text: string) => void;
}

type LengthType = 'simple' | 'medium' | 'long';

export const LengthVariationsDropdown = ({ text, onApplyToWorkspace }: LengthVariationsDropdownProps) => {
  const [variations, setVariations] = useState<LengthVariations | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [selectedType, setSelectedType] = useState<LengthType>('medium');
  const [selectedCount, setSelectedCount] = useState<number>(3);
  const [selectedVariation, setSelectedVariation] = useState<LengthVariation | null>(null);
  const [copiedId, setCopiedId] = useState<string | null>(null);

  useEffect(() => {
    if (text.trim().length >= 20) {
      fetchVariations();
    }
  }, [text]);

  const fetchVariations = async () => {
    if (!text.trim() || text.length < 20) return;
    
    setIsLoading(true);
    try {
      const result = await getLengthVariations(text);
      setVariations(result);
      // Auto-select first medium variation
      if (result.medium?.[0]) {
        setSelectedVariation(result.medium[0]);
      }
    } catch (error) {
      console.error('Error fetching length variations:', error);
      toast.error('Failed to generate length variations');
    } finally {
      setIsLoading(false);
    }
  };

  const copyToClipboard = async (variation: LengthVariation) => {
    await navigator.clipboard.writeText(variation.text);
    setCopiedId(variation.id);
    toast.success('Copied!');
    setTimeout(() => setCopiedId(null), 2000);
  };

  const downloadAsPdf = async (variation: LengthVariation) => {
    try {
      // Create a simple PDF-like text file with content
      const content = `
EchoWrite Generated Content
============================

Type: ${selectedType.charAt(0).toUpperCase() + selectedType.slice(1)}
Word Count: ${variation.wordCount}

---

${variation.text}

---
Generated by EchoWrite AI
      `.trim();

      const blob = new Blob([content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `echowrite-${selectedType}-${Date.now()}.txt`;
      link.click();
      URL.revokeObjectURL(url);
      
      toast.success('Downloaded as text file!');
    } catch (error) {
      toast.error('Failed to download');
    }
  };

  const lengthTypes: { id: LengthType; label: string; icon: typeof FileText; description: string }[] = [
    { id: 'simple', label: 'Simple', icon: AlignLeft, description: 'Short & concise' },
    { id: 'medium', label: 'Medium', icon: FileText, description: 'Balanced length' },
    { id: 'long', label: 'Long', icon: BookOpen, description: 'Detailed & comprehensive' },
  ];

  const currentVariations = variations?.[selectedType]?.slice(0, selectedCount) || [];

  if (isLoading) {
    return (
      <div className="neu-flat rounded-2xl p-8 flex flex-col items-center justify-center">
        <RefreshCw className="w-8 h-8 text-primary animate-spin mb-4" />
        <p className="text-xs font-bold text-muted-foreground uppercase tracking-wider">
          Generating variations...
        </p>
      </div>
    );
  }

  if (!variations) {
    return (
      <div className="neu-pressed rounded-2xl p-8 text-center opacity-70">
        <p className="text-xs font-bold text-muted-foreground uppercase tracking-wider">
          Length Variations
        </p>
        <p className="text-[10px] text-muted-foreground mt-2">
          Generate content above to see length variations
        </p>
      </div>
    );
  }

  return (
    <div className="neu-flat rounded-2xl p-6">
      {/* Controls Row */}
      <div className="flex flex-wrap items-center gap-4 mb-6">
        {/* Length Type Tabs */}
        <div className="flex gap-2">
          {lengthTypes.map((type) => {
            const Icon = type.icon;
            return (
              <button
                key={type.id}
                onClick={() => {
                  setSelectedType(type.id);
                  setSelectedVariation(variations?.[type.id]?.[0] || null);
                }}
                className={cn(
                  'flex items-center gap-2 px-4 py-2.5 rounded-xl transition-all',
                  selectedType === type.id
                    ? 'style-chip-active'
                    : 'neu-flat text-muted-foreground hover:text-foreground'
                )}
              >
                <Icon className="w-4 h-4" />
                <span className="text-xs font-bold uppercase">{type.label}</span>
              </button>
            );
          })}
        </div>

        {/* Count Dropdown */}
        <div className="flex items-center gap-2">
          <span className="text-xs text-muted-foreground">Show:</span>
          <Select value={selectedCount.toString()} onValueChange={(v) => setSelectedCount(parseInt(v))}>
            <SelectTrigger className="w-20 h-10 neu-flat border-0 text-sm font-semibold">
              <SelectValue />
            </SelectTrigger>
            <SelectContent className="neu-flat border-border">
              {[1, 2, 3, 4, 5].map((num) => (
                <SelectItem key={num} value={num.toString()}>
                  {num} {num === 1 ? 'item' : 'items'}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      </div>

      {/* Variations List */}
      <div className="space-y-4">
        {currentVariations.map((variation, index) => (
          <div
            key={variation.id}
            onClick={() => setSelectedVariation(variation)}
            className={cn(
              'p-5 rounded-xl cursor-pointer transition-all',
              selectedVariation?.id === variation.id
                ? 'neu-pressed ring-2 ring-primary'
                : 'neu-flat hover:scale-[1.01]'
            )}
          >
            {/* Header */}
            <div className="flex items-center justify-between mb-3">
              <span className="text-xs font-bold text-primary uppercase">
                Variation {index + 1}
              </span>
              <div className="flex items-center gap-3">
                <span className="text-[10px] text-muted-foreground bg-muted px-2 py-1 rounded-lg">
                  {variation.wordCount} words
                </span>
                
                {/* Copy Button */}
                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    copyToClipboard(variation);
                  }}
                  className="p-2 rounded-lg neu-button hover:text-primary transition-colors"
                  title="Copy"
                >
                  {copiedId === variation.id ? (
                    <CheckCircle2 className="w-4 h-4 text-primary" />
                  ) : (
                    <Copy className="w-4 h-4" />
                  )}
                </button>
                
                {/* PDF Download Button */}
                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    downloadAsPdf(variation);
                  }}
                  className="p-2 rounded-lg neu-button hover:text-primary transition-colors"
                  title="Download as PDF"
                >
                  <Download className="w-4 h-4" />
                </button>
              </div>
            </div>

            {/* Content */}
            <p className="text-sm text-foreground leading-relaxed whitespace-pre-wrap">
              {variation.text}
            </p>

            {/* Apply Button */}
            {selectedVariation?.id === variation.id && (
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  onApplyToWorkspace(variation.text);
                }}
                className="mt-4 w-full py-3 primary-button rounded-xl flex items-center justify-center gap-2 text-xs"
              >
                Apply to Workspace
                <ArrowRight className="w-4 h-4" />
              </button>
            )}
          </div>
        ))}
      </div>
      
      {currentVariations.length === 0 && (
        <div className="text-center py-8">
          <p className="text-xs text-muted-foreground">
            No {selectedType} variations available
          </p>
        </div>
      )}
    </div>
  );
};
