import { useState } from 'react';
import { LengthVariations, getLengthVariations, LengthVariation } from '@/services/aiService';
import { Copy, CheckCircle2, ArrowRight, RefreshCw, FileText, AlignLeft, BookOpen, Share2, Mail, MessageCircle, Download, Wand2 } from 'lucide-react';
import { toast } from 'sonner';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Slider } from "@/components/ui/slider";
import { cn } from '@/lib/utils';

interface LengthVariationsPanelProps {
  text: string;
  onApplyToWorkspace: (text: string) => void;
}

type LengthType = 'simple' | 'medium' | 'long';

export const LengthVariationsPanel = ({ text, onApplyToWorkspace }: LengthVariationsPanelProps) => {
  const [variations, setVariations] = useState<LengthVariations | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [selectedType, setSelectedType] = useState<LengthType>('medium');
  const [selectedVariation, setSelectedVariation] = useState<LengthVariation | null>(null);
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [sliderValue, setSliderValue] = useState<number[]>([3]); // 1-5 slider, default 3

  // Map slider value to number of variations to show
  const variationCount = sliderValue[0];

  // Map slider position to length type
  const getLengthTypeFromSlider = (value: number): LengthType => {
    if (value <= 2) return 'simple';
    if (value <= 4) return 'medium';
    return 'long';
  };

  const handleSliderChange = (value: number[]) => {
    setSliderValue(value);
    const newType = getLengthTypeFromSlider(value[0]);
    if (newType !== selectedType) {
      setSelectedType(newType);
      setSelectedVariation(variations?.[newType]?.[0] || null);
    }
  };

  const fetchVariations = async () => {
    if (!text.trim() || text.length < 10) {
      toast.error('Please enter at least 10 characters');
      return;
    }
    
    setIsLoading(true);
    try {
      const result = await getLengthVariations(text);
      setVariations(result);
      // Auto-select first variation based on slider
      const type = getLengthTypeFromSlider(sliderValue[0]);
      if (result[type]?.[0]) {
        setSelectedVariation(result[type][0]);
      }
      toast.success('Variations generated!');
    } catch (error) {
      console.error('Error fetching length variations:', error);
      toast.error('Failed to generate variations');
    } finally {
      setIsLoading(false);
    }
  };

  const copyToClipboard = async (variation: LengthVariation) => {
    await navigator.clipboard.writeText(variation.text);
    setCopiedId(variation.id);
    toast.success('Copied!');
    setTimeout(() => setCopiedId(null), 2000);
  };

  const shareToWhatsApp = (variation: LengthVariation) => {
    const text = encodeURIComponent(variation.text);
    window.open(`https://wa.me/?text=${text}`, '_blank');
  };

  const shareToEmail = (variation: LengthVariation) => {
    const subject = encodeURIComponent('Shared from EchoWrite');
    const body = encodeURIComponent(variation.text);
    window.open(`mailto:?subject=${subject}&body=${body}`, '_blank');
  };

  const downloadAsPdf = async (variation: LengthVariation) => {
    // Create a simple HTML document and print as PDF
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
          <title>EchoWrite Export</title>
          <style>
            body { font-family: Georgia, serif; padding: 40px; line-height: 1.8; }
            h1 { font-size: 18px; color: #333; margin-bottom: 20px; }
            p { font-size: 14px; color: #444; white-space: pre-wrap; }
            .footer { margin-top: 40px; font-size: 11px; color: #888; }
          </style>
        </head>
        <body>
          <h1>EchoWrite - ${selectedType.charAt(0).toUpperCase() + selectedType.slice(1)} Variation</h1>
          <p>${variation.text}</p>
          <div class="footer">Generated by EchoWrite AI Writing Assistant</div>
        </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
    toast.success('Opening print dialog...');
  };

  const lengthLabels = {
    simple: { icon: AlignLeft, label: 'Simple', color: 'text-accent' },
    medium: { icon: FileText, label: 'Medium', color: 'text-primary' },
    long: { icon: BookOpen, label: 'Long', color: 'text-secondary' },
  };

  const currentLengthType = getLengthTypeFromSlider(sliderValue[0]);
  const CurrentIcon = lengthLabels[currentLengthType].icon;
  const currentVariations = variations?.[currentLengthType]?.slice(0, variationCount) || [];

  return (
    <div className="neu-flat rounded-2xl p-5">
      {/* Header with Slider and Generate Button */}
      <div className="flex items-center gap-4 mb-5">
        {/* Length Type Icon */}
        <div className={cn(
          'w-10 h-10 rounded-xl neu-convex flex items-center justify-center shrink-0',
          lengthLabels[currentLengthType].color
        )}>
          <CurrentIcon className="w-5 h-5" />
        </div>
        
        {/* Slider Container */}
        <div className="flex-1">
          <div className="flex items-center justify-between mb-2">
            <span className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider">
              Variations: {variationCount}
            </span>
            <span className={cn(
              'text-[10px] font-bold uppercase px-2 py-0.5 rounded-lg',
              currentLengthType === 'simple' && 'bg-accent/20 text-accent',
              currentLengthType === 'medium' && 'bg-primary/20 text-primary',
              currentLengthType === 'long' && 'bg-secondary/20 text-secondary-foreground'
            )}>
              {lengthLabels[currentLengthType].label}
            </span>
          </div>
          <div className="flex items-center gap-3">
            <span className="text-[10px] text-muted-foreground">Min</span>
            <Slider
              value={sliderValue}
              onValueChange={handleSliderChange}
              min={1}
              max={5}
              step={1}
              className="flex-1"
            />
            <span className="text-[10px] text-muted-foreground">Max</span>
          </div>
        </div>

        {/* Generate Button */}
        <button
          onClick={fetchVariations}
          disabled={isLoading || !text.trim()}
          className={cn(
            'flex items-center gap-2 px-5 py-3 rounded-xl font-bold text-xs transition-all shrink-0',
            isLoading ? 'neu-pressed opacity-70' : 'primary-button hover:scale-[1.02]'
          )}
        >
          {isLoading ? (
            <>
              <RefreshCw className="w-4 h-4 animate-spin" />
              <span>Generating...</span>
            </>
          ) : (
            <>
              <Wand2 className="w-4 h-4" />
              <span>Generate</span>
            </>
          )}
        </button>
      </div>

      {/* Variations Display */}
      {isLoading ? (
        <div className="neu-pressed rounded-xl p-8 flex flex-col items-center justify-center">
          <RefreshCw className="w-8 h-8 text-primary animate-spin mb-4" />
          <p className="text-xs font-bold text-muted-foreground uppercase tracking-wider">
            Generating {variationCount} {currentLengthType} variations...
          </p>
        </div>
      ) : !variations ? (
        <div className="neu-pressed rounded-xl p-8 text-center opacity-70">
          <p className="text-xs font-bold text-muted-foreground uppercase tracking-wider">
            📝 Length Variations
          </p>
          <p className="text-[10px] text-muted-foreground mt-2">
            Enter text in workspace and click Generate
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {currentVariations.map((variation, index) => (
            <div
              key={variation.id}
              onClick={() => setSelectedVariation(variation)}
              className={cn(
                'p-4 rounded-xl cursor-pointer transition-all',
                selectedVariation?.id === variation.id
                  ? 'neu-pressed ring-2 ring-primary'
                  : 'neu-flat hover:scale-[1.005]'
              )}
            >
              {/* Header */}
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center gap-2">
                  <span className="text-[10px] font-bold text-primary uppercase">
                    ✨ Variation {index + 1}
                  </span>
                  <span className="text-[9px] text-muted-foreground bg-muted px-1.5 py-0.5 rounded">
                    {variation.wordCount} words
                  </span>
                </div>
                <div className="flex items-center gap-1.5">
                  {/* PDF Download */}
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      downloadAsPdf(variation);
                    }}
                    className="p-1.5 rounded-lg neu-button hover:text-primary transition-colors"
                    title="Download as PDF"
                  >
                    <Download className="w-3.5 h-3.5" />
                  </button>
                  
                  {/* Copy */}
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      copyToClipboard(variation);
                    }}
                    className="p-1.5 rounded-lg neu-button hover:text-primary transition-colors"
                    title="Copy"
                  >
                    {copiedId === variation.id ? (
                      <CheckCircle2 className="w-3.5 h-3.5 text-primary" />
                    ) : (
                      <Copy className="w-3.5 h-3.5" />
                    )}
                  </button>
                  
                  {/* Share Menu */}
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <button
                        onClick={(e) => e.stopPropagation()}
                        className="p-1.5 rounded-lg neu-button hover:text-primary transition-colors"
                        title="Share"
                      >
                        <Share2 className="w-3.5 h-3.5" />
                      </button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end" className="neu-flat border-border">
                      <DropdownMenuItem 
                        onClick={(e) => {
                          e.stopPropagation();
                          shareToWhatsApp(variation);
                        }}
                        className="gap-2 cursor-pointer text-xs"
                      >
                        <MessageCircle className="w-3.5 h-3.5 text-accent" />
                        WhatsApp
                      </DropdownMenuItem>
                      <DropdownMenuItem 
                        onClick={(e) => {
                          e.stopPropagation();
                          shareToEmail(variation);
                        }}
                        className="gap-2 cursor-pointer text-xs"
                      >
                        <Mail className="w-3.5 h-3.5 text-primary" />
                        Email
                      </DropdownMenuItem>
                    </DropdownMenuContent>
                  </DropdownMenu>
                </div>
              </div>

              {/* Content */}
              <p className="text-sm text-foreground leading-relaxed whitespace-pre-wrap">
                {variation.text}
              </p>

              {/* Apply Button */}
              {selectedVariation?.id === variation.id && (
                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    onApplyToWorkspace(variation.text);
                  }}
                  className="mt-3 w-full py-2.5 primary-button rounded-lg flex items-center justify-center gap-2 text-xs"
                >
                  Apply to Workspace
                  <ArrowRight className="w-3.5 h-3.5" />
                </button>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
